### ISSUE TITLE
Add a way to exit the launcher without executing an action

### ISSUE THREAD

**Issue by JCallicoat** [mudler/golauncher#1]
It seems like there should be a way to close the launcher without taking any action. I would expect escape, or enter if nothing was typed, to close the launcher without doing anything.

**Comment by mudler** [comment]
Hi! 

thanks for raising an issue.. yes, sounds reasonable indeed and It was in the back of my head too with more or less the same logic ideas in it, confirming that's the way to go.

**Comment by mudler** [comment]
Fixed in https://github.com/mudler/golauncher/releases/tag/0.2.2
